# Generated by Django 3.2.16 on 2023-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipconfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('net_mask', models.CharField(max_length=100)),
            ],
        ),
    ]
